### ISSUE TITLE
Problem with Anaconda

### ISSUE THREAD

**Issue by D13G083** [harvimt/quamash#121]
Hi. I am trying to install Anaconda. I have Windows 10. Here are the steps I have taken:

Login to https://www.anaconda.com/products/individual
I download https://repo.anaconda.com/archive/Anaconda3-2020.02-Windows-x86_64.exe
I install Anaconda (run) as Administrator
Installation steps
- Install for: Just me
- destination Folder: C:\anaconda3. 
- Advanced Options: Register Anaconda3 as my default Python 3.7

I run the Anaconda Prompt (with Administrator permissions) the following: anaconda-navigator
Errors that appear to me:
- ModuleNotFoundError: No module named 'PySide'
- PythonQtError ('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

I proceed to install PySide: pip install PySide2
Successfully installed: Successfully installed PySide2-5.14.2.1 shiboken2-5.14.2.1

Within the environment variables, in system variables I have configured the following:
Variable: Path
Value: C: \ anaconda3 \ Lib \ site-packages \ PySide2 \

Variable: QT_PLUGIN_PATH
Value: C: \ anaconda3 \ Lib \ site-packages \ PySide2 \ plugins

I run anaconda-navigator again

I see the Anaconda icon when it starts to load the applications it appears to me:

Message: (base) C:\WINDOWS\system32>anaconda-navigator
Traceback (most recent call last):
  File "C:\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 541, in setup
    self.post_setup(conda_data=conda_data)
  File "C:\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 578, in post_setup
    self.tab_home.setup(conda_data)
  File "C:\anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 168, in setup
    self.set_environments(environments)
  File "C:\anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 175, in set_environments
    self.combo.currentIndexChanged.disconnect()
**RuntimeError: Failed to disconnect signal currentIndexChanged(int).**

I hope you can help me.

Regards.

**Comment by harvimt** [comment]
I don't support the Anaconda packages.

They were produced @aknuds1 I think, but it's not clear to me what package you're installing with anaconda.

I really need to release the new version to PyPI which doesn't include the module itself in setup.py, and therefore does not need a version of Qt installed during setup. That being said the packages in PyPI now are wheels (or I think there are wheels and sdist), if you install the wheel the setup.py problem goes away.

I highly recommend migrating to `poetry` for dependency management, it's standardized and supports pep517 and is generally pleasant to use in ways that I found anaconda never was, but I suppose your mileage may vary.

try:
- installing from the tests-2019 branch which has the pyproject.toml + new setup.py that does not `import quamash`
- installing the wheel directly (instead of `pip install quamash`) download and install https://files.pythonhosted.org/packages/89/41/ba1396ebed0dcfd09854addea45323c93f498dc7c45d855943ab31791194/Quamash-0.6.1-py3-none-any.whl

I think there's a flag to pip to force it to use the .whl and not the sdist, but I forget it
